### ISSUE TITLE
Error: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/stellar-experiments#1]
When running the program, we get:

```
Error: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }
```

Find out and resolve why we are getting disconnected.

**Comment by b-yap** [comment]
Performed a `cargo run` and i don't get this error, but i get stuck.

I tried to use js-stellar-node-connector's `examples:connect`, and applied the [suggestion](https://github.com/stellarbeat/js-stellar-node-connector/issues/25#issuecomment-1191289171) but I still get the error _wrong protocol version_

**Comment by b-yap** [comment]
update: the suggestion actually worked.

**Comment by b-yap** [comment]
@ashneverdawn  can we already close this issue, as it's not occurring anymore?

**Comment by ashneverdawn** [comment]
Yes, thanks.
